#data ingestion config
data_source:
  raw_data:
    pdf_path: data\raw_data\data.pdf
  normalized_data:
    unstructured_text_path: data\normalized_data\data.md
    structured_text_path: data\normalized_data\clean_data.md