#data ingestion config
data_source:
  raw_data:
    pdf_path: data\raw_data\data.pdf
  normalized_data:
    unstructured_text_path: data\normalized_data\data.md
    structured_text_path:
      data : data\normalized_data\structured_data.md
      volume_1: data\normalized_data\clean_data_volume_1.md
      volume_2: data\normalized_data\clean_data_volume_2.md
  jsonified_data:
    volume_1: data\jsonified_data\volume_1.json
    volume_2: data\jsonified_data\volume_2.json

#data chunking and embedding config
chunking:
  chunk_size: 450
  chunk_overlap: 0
embedding:
  embedding_model: "text-embedding-3-small"

#retriever config
retriever:
  vector_store_path: "C:/vscode/graph-rag/Source/data/vector_stores/chunk_size_1000"
  search_type: "mmr"
  k: 15

#LLM config
llm:
  model_name: "gpt-4.1-nano"

#evaluation config
evaluation:
  ground_truth_path: C:\vscode\graph-rag\Source\evaluation\ground_truth\ground_truth.jsonl
  output_path: C:/vscode/graph-rag/evaluation/results/evaluation_results.json