#data ingestion config
data_source:
  raw_data:
    pdf_path: data\raw_data\data.pdf
  normalized_data:
    unstructured_text_path: data\normalized_data\data.md
    structured_text_path:
      data : data\normalized_data\structured_data.md
      volume_1: data\normalized_data\clean_data_volume_1.md
      volume_2: data\normalized_data\clean_data_volume_2.md
  jsonified_data:
    volume_1: data\jsonified_data\volume_1.json
    volume_2: data\jsonified_data\volume_2.json

#data chunking and embedding config
chunking:
  chunk_size: 1000
  chunk_overlap: 250
embedding:
  embedding_model: "text-embedding-3-small"

#retriever config
retriever:
  vector_store_path: "data/vector_store"
  search_type: "similarity"
  k: 5

#LLM config
llm:
  model_name: "gpt-4o-mini"